---
title: Python 异常捕获
date: 2017/07/13 15:03:18
categories: 
- Python
- 笔记
tags: 
- try
---

### 错误和异常

#### 1.概念

> 错误：语法错误【解析错误】，例如：缩进，缺少冒号等
>
> 异常：当程序运行的时候【可能性】
>
> 问题：当程序中遇到异常，程序会终止在异常处，后面的代码没有执行的机会
>
> 解决：跳过异常，让后面的代码继续执行【屏蔽异常】

#### 2.常见的异常

> AttributeError：试图访问一个对象没有的成员【属性和方法】
>
> ValueError：值错误，传入了一个不期望的值
>
> ImportError:无法导入模块或者包：基本上路径问题
>
> IndexError:访问了不在范围内的索引
>
> KeyError:试图访问字典中不存在的键
>
> NameError；使用了还没被赋值的变量
>
> TypeError:传入的数据类型和要求不符合
>
> UnboundLocalError:试图访问一个还未被设置的局部变量：基本上是存在一个和局部变量重名的全局变量，使用global声明
>
> SyntaxError:Python非法代码，代码无法编译

#### 3.处理异常

> 处理异常的方式：捕获和抛出

##### 3.1捕获try-except-else

> 语法：
>
> try:
>
> ​	代码块1
>
> except  错误表示码 as  异常的对象:
>
> ​	代码块2
>
> except  错误表示码 as  异常的对象:
>
> ​	代码块3
>
> ....
>
> else:
>
> ​	代码块n
>
> 说明：
>
> ​	a.代码块1:try的区域属于监测区，为了监测其中的代码有没有异常
>
> ​		情况一：如果有异常：代码会终止在异常的代码处，去执行excepr代码块
>
> ​		情况二：如果没有异常：会将try中的代码全部执行完，跳过except代码块
>
> ​	b.except  错误表示码 as  异常的对象:
>
> ​		错误表示码：可能会出现的异常对应的系统类
>
> ​		异常的对象:一般用e表示【e只是一个变量名，合法的标识符即可】
>
> ​	c.else：可有可无，只有当try中的代码没有任何异常的时候才会被执行
>
> 代码演示：
>
> ```python
> #1.使用try-except语句：except带异常类型
> """
> try:
>     num1 = int(input("输入一个数字："))  # ValueError: invalid literal for int() with base 10: 'fagh'
>     print(num1)
>     print("over")
> except ValueError as e:
>     print("except语句执行了")
>     #异常信息的描述，在异常类的内部 已经重写了__str__函数
>     print(e)
> print("hello")
> 
> 
> #2.一个try语句后面可以跟多个except语句
> #try中可能会出现的异常依次列出来
> #注意1：如果try中的语句出现异常，则会去后面的excpet分支从上往下依次进行匹配,
> # 如果匹配上，则执行相应的except语句，如果匹配不上,异常仍然存在，并没有被屏蔽掉
> #注意2：不管有多少个except分支，根据try中出现的异常，都只会执行其中的一个except分支
> try:
>     num1 = int(input("输入一个数字："))  # ValueError: invalid literal for int() with base 10: 'fagh'
>     print(num1)
>     print(3 / num1)  # ZeroDivisionError: division by zero
>     print("over")
> except ZeroDivisionError as e:
>     print("ZeroDivisionError被执行了")
>     print(e)
> except ValueError as e:
>     print("ValueError语句执行了")
>     print(e)
> 
> print("hello")
> 
> 
> #3.使用try-except语句：except语句后面不带任何类型
> #注意：except分支可以匹配任意的异常类型
> try:
>     num1 = int(input("输入一个数字："))
>     print(num1)
>     print("over")
> except:
>     print("except语句执行了")
> print("hello")
> 
> 
> #4.except分支后面可以跟一个元组，元组的元素为try中能出现的所有的异常的类型
> #不管出现哪种异常，都会进入except分支中执行
> try:
>     num1 = int(input("输入一个数字："))
>     print(num1)
>     print(3 / num1)
>     print("over")
> except (ValueError,ZeroDivisionError):
>     print("except语句执行了")
> print("hello")
> 
> 
> #5.except后面跟异常的父类
> #所有异常的父类是Exception【object】
> #注意：如果在except分支中出现父类Exception，而且Exception出现在except分支的第一个，则所有的异常都会执行该分支
> #如果Exception出现在except分支的中间或者后面，则按照类型从上往下依次匹配
> try:
>     num1 = int(input("输入一个数字："))
>     print(num1)
>     print(3 / num1)
>     print("over")
> except Exception as e:
>     print("Exception语句执行了")
> except ZeroDivisionError as e:
>     print("ZeroDivisionError语句执行了")
> except ValueError as e:
>     print("ValueError语句执行了")
> 
> print("hello")
> 
> 
> 
> #6.else分支
> try:
>     num1 = int(input("输入一个数字："))
>     print(num1)
>     print("over")
> except:
>     print("except语句执行了")
> else:
>     print("else分支被执行了")
> print("hello")
> """
> 
> #7.try-except不仅仅可以直接处理可能存在异常的代码，也可以处理可能存在异常的代码所在的函数调用
> def show():
>     #try-except
>     num1 = int(input("输入一个数字："))
>     print(num1)
>     print("over")
> 
> try:
>     show()
> except ValueError as e:
>     print(e)
> ```

##### 3.2捕获try-except-finally【掌握】

> 作用：不管try中的代码有没有异常，finally分支都会被执行
>
> 可以在finally中定义清理行为，比如：关闭文件，关闭数据库等
>
> 语法：
>
> try:
>
> ​	代码块1
>
> except  错误表示码 as  异常的对象:
>
> ​	代码块2
>
> except  错误表示码 as  异常的对象:
>
> ​	代码块3
>
> ....
>
> finally:
>
> ​	代码块n
>
> 代码演示：
>
> ```python
> #1.直接使用
> """
> try:
>     list1 = [54,45,45,4]
>     for i in range(len(list1)):
>         print(list1[i])
> 
> except IndexError as e:
>     print(e)
> finally:
>     print("finally被执行了")
> """
> 
> #2.特殊情况:当try或者except分支中出现return，finally仍然会被执行
> def show():
>     try:
>         list1 = [54, 45, 45, 4]
>         for i in range(10):
>             print(list1[i])
> 
>         return
> 
>     except IndexError as e:
>         print(e)
>         return
>     finally:
>         print("finally被执行了")
> 
> show()
> ```

##### 3.3抛出raise关键字

> raise;抛出一个指定的异常对象
>
> 语法：
>
> raise   创建出来的异常对象-----》raise   异常类(“异常信息的描述”)
>
> 使用场景：自定义异常中
>
> 注意：通过raise抛出的异常，最终还是需要通过try-except语句进行捕获
>
> 代码演示：
>
> ```python
> #不管是通过代码出现的异常，还是通过异常类创建出来的异常，都属于异常的对象
> #print(num)
> #raise NameError("出现错误")
> 
> #print(10 / 0)
> #raise  ZeroDivisionError("不能除以0")
> 
> try:
>     #print(10 / 0)
>     raise ZeroDivisionError("不能除以0")
> except ZeroDivisionError as e:
>     print(e)
> 
> print("helo")
> ```

##### 3.4断言assert

> 断言：在代码出现异常之前，做一个预测
>
> 代码演示：
>
> ```python
> def func(num1,num2):
>     #断言
>     #在可能存在异常的代码之前进行预测，如果条件成立，则代码正常执行，得到结果
>     #如果条件不成立，则出现一个异常AssertionError，而且异常的信息描述是自定义的字符串
>     #assert  (num2 != 0),"参数num2不能为0"
>     #相当于在异常之前做了一个判断，等价于下面的代码：
>     if num2 == 0:
>         return
>     return  num1 / num2
> 
> 
> print(func(10,327))
> print(func(23,0))
> 
> ```

#### 4.异常嵌套

> 语法：
>
> try:
>
> ​	if/for/while
>
> except  错误表示码 as  异常的对象:
>
> ​	代码块2
>
> ​	try:
>
> ​	
>
> ​	except  错误表示码 as  异常的对象:
>
> ​		代码块21
>
> ​	
>
> finally:
>
> ​	try:
>
> ​		if/for/while
>
> ​	except  错误表示码 as  异常的对象:
>
> ​		代码块3
>
> 说明：类似于if/for/while的嵌套，嵌套的层数不超过3层	
>
> 代码演示：
>
> ```python
> #
> print("我要去拉萨")
> 
> try:
>     print("我要做飞机过去")
>     raise Exception("由于天气大雾，飞机不能起飞")
>     print("到拉萨了，拉萨真漂亮")
> except Exception as e:
>     print(e)
>     try:
>         print("我要做火车过去")
>         raise Exception("由于大暴雨，铁路断了，火车停运")
>         print("到拉萨了，拉萨真漂亮")
>     except Exception as e:
>         print(e)
>         print("骑自行车过去")
>         print("到拉萨了，拉萨真漂亮")
> ```

#### 5.自定义异常

> 当需要处理生活中的问题，系统的异常将不满足不了需求，就需要自定义异常
>
> 实现方式：
>
> ​	a.自定义一个类，继承自系统的异常类【Exception或者BaseException】
>
> ​	b.书写构造函数，定义一个属性，用来描述异常信息
>
> ​	c.重写__str__函数，打印异常对象获取异常信息
>
> ​	d.自定义一个成员函数，用来处理自己的异常
>
> 代码演示：
>
> ```python
> class MyException(Exception):
>     def __init__(self,msg):
>         #调用父类的构造函数，主要为了继承系统的异常机制
>         super(MyException,self).__init__()
>         self.msg = msg
> 
>     def __str__(self):
>         return self.msg
> 
>     def handle(self):
>         print("出现异常，执行该函数")
> 
> try:
>     raise MyException("异常信息")
> except MyException as e:
>     print(e)
>     e.handle()
> ```

### 

